from os import getenv
from dotenv import load_dotenv

load_dotenv()

USE_AI=getenv("USE_AI")
OLLAMA_HOST=getenv("OLLAMA_HOST")
OLLAMA_MODEL=getenv("OLLAMA_MODEL")
EXCLUDE_SYMBOL=getenv("EXCLUDE_SYMBOL")
AUTO_EXECUTE_ORDERS=getenv("AUTO_EXECUTE_ORDERS")
BNC_URL=getenv("BNC_URL")
BNC_TARJETA=getenv("BNC_TARJETA")
BNC_CEDULA=getenv("BNC_CEDULA")
BNC_PASSWORD=getenv("BNC_PASSWORD")
FETCH_BNC_BALANCE=getenv("FETCH_BNC_BALANCE")
BNC_HEADLESS=getenv("BNC_HEADLESS")
MERCOSUR_EMAIL=getenv("MERCOSUR_EMAIL")
MERCOSUR_PASSWORD=getenv("MERCOSUR_PASSWORD")
MERCOSUR_CLAVE_OPERACIONES=getenv("MERCOSUR_CLAVE_OPERACIONES")
MERCOSUR_LOGIN_URL=getenv("MERCOSUR_LOGIN_URL", "https://www.mercosur.com.ve/login")
MERCOSUR_COTIZACIONES_URL=getenv("MERCOSUR_COTIZACIONES_URL", "https://www.mercosur.com.ve/cotizaciones")
MERCOSUR_SALDOS_URL=getenv("MERCOSUR_SALDOS_URL", "https://www.mercosur.com.ve/saldos")
MERCOSUR_MOVIMIENTOS_URL=getenv("MERCOSUR_MOVIMIENTOS_URL", "https://www.mercosur.com.ve/movimientos")
MERCOSUR_COMPRA_VENTA_URL=getenv("MERCOSUR_COMPRA_VENTA_URL", "https://www.mercosur.com.ve/compra-venta")
MERCOSUR_ORDENES_URL=getenv("MERCOSUR_ORDENES_URL", "https://www.mercosur.com.ve/ordenes")
MERCOSUR_TRANSFERENCIAS_URL=getenv("MERCOSUR_TRANSFERENCIAS_URL", "https://www.mercosur.com.ve/transferencias")
MERCOSUR_PERFIL_URL=getenv("MERCOSUR_PERFIL_URL", "https://www.mercosur.com.ve/perfil")
MERCOSUR_LOGOUT_URL=getenv("MERCOSUR_LOGOUT_URL", "https://www.mercosur.com.ve/logout")
MERCOSUR_HEADLESS=getenv("MERCOSUR_HEADLESS", "True")
TOKEN_FILE=getenv("TOKEN_FILE", "data/session_token.json")
TIMEOUT=getenv("TIMEOUT", "60")
DATA_FILE=getenv("DATA_FILE", "data/data.json")
EXCLUDE_SYMBOLS=getenv("EXCLUDE_SYMBOLS", "VE")
NEWS_FEEDS=getenv("NEWS_FEEDS", "https://www.mercosur.com.ve/noticias")
LOG_LEVEL=getenv("LOG_LEVEL", "INFO")
DATA_DIR=getenv("DATA_DIR", "data")
